name: Web App CI/CD Flow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 11 (Zulu)
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

   docker-build-push:
     runs-on: ubuntu-latest
     needs: build
     steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker image
        run: docker build -t takue05/web-app-docker:latest .

      - name: Push Docker image to Docker Hub
        run: docker push takue05/web-app-docker:latest

   deploy:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Run SSH Command
        run: ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p 822 TakudzwaNhema@20.84.103.115 "cd PROJECTS/my-web-app && docker pull takue05/web-app-docker:latest && docker-compose up -d"
